{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
{{ $gateway := index .Values "gateways" "istio-ingressgateway" }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ $gateway.name | default "istio-ingressgateway" }}

{{- if or (not $gateway.namespace) (eq $gateway.name "istio-ingressgateway") }}
  namespace: {{ .Release.Namespace }}
{{- else }}
  namespace: {{ $gateway.namespace }}
{{- end }}
  labels:
    maistra-version: 2.0.0
{{ $gateway.labels | toYaml | trim | indent 4 }}
    release: {{ .Release.Name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
{{ $gateway.labels | toYaml | trim | indent 6 }}
      release: {{ .Release.Name }}
{{- end }}
