{{ $gateway := index .Values "gateways" "istio-ingressgateway" }}
apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
metadata:
  name: {{ $gateway.name | default "istio-ingressgateway" }}-service-account

{{- if or (not $gateway.namespace) (eq $gateway.name "istio-ingressgateway") }}
  namespace: {{ .Release.Namespace }}
{{- else }}
  namespace: {{ $gateway.namespace }}
{{- end }}
  labels:
    maistra-version: 2.0.0
{{ $gateway.labels | toYaml | trim | indent 4 }}
    release: {{ .Release.Name }}
