// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArchSchedulingPrefs) DeepCopyInto(out *ArchSchedulingPrefs) {
	*out = *in
	if in.AMD64 != nil {
		in, out := &in.AMD64, &out.AMD64
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	if in.S390X != nil {
		in, out := &in.S390X, &out.S390X
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	if in.PPC64LE != nil {
		in, out := &in.PPC64LE, &out.PPC64LE
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArchSchedulingPrefs.
func (in *ArchSchedulingPrefs) DeepCopy() *ArchSchedulingPrefs {
	if in == nil {
		return nil
	}
	out := new(ArchSchedulingPrefs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerConfig) DeepCopyInto(out *AutoscalerConfig) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	if in.TargetCPUUtilizationPercentage != nil {
		in, out := &in.TargetCPUUtilizationPercentage, &out.TargetCPUUtilizationPercentage
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerConfig.
func (in *AutoscalerConfig) DeepCopy() *AutoscalerConfig {
	if in == nil {
		return nil
	}
	out := new(AutoscalerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CitadelConfig) DeepCopyInto(out *CitadelConfig) {
	*out = *in
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
	if in.SelfSigned != nil {
		in, out := &in.SelfSigned, &out.SelfSigned
		if *in == nil {
			*out = nil
		} else {
			*out = new(bool)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CitadelConfig.
func (in *CitadelConfig) DeepCopy() *CitadelConfig {
	if in == nil {
		return nil
	}
	out := new(CitadelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonGatewayConfig) DeepCopyInto(out *CommonGatewayConfig) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]v1.ServicePort, len(*in))
		copy(*out, *in)
	}
	in.Autoscaler.DeepCopyInto(&out.Autoscaler)
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		if *in == nil {
			*out = nil
		} else {
			*out = new(v1.ResourceRequirements)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonGatewayConfig.
func (in *CommonGatewayConfig) DeepCopy() *CommonGatewayConfig {
	if in == nil {
		return nil
	}
	out := new(CommonGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DebugConfig) DeepCopyInto(out *DebugConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DebugConfig.
func (in *DebugConfig) DeepCopy() *DebugConfig {
	if in == nil {
		return nil
	}
	out := new(DebugConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfig) DeepCopyInto(out *DeploymentConfig) {
	*out = *in
	out.Image = in.Image
	in.Autoscaler.DeepCopyInto(&out.Autoscaler)
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		if *in == nil {
			*out = nil
		} else {
			*out = new(v1.ResourceRequirements)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfig.
func (in *DeploymentConfig) DeepCopy() *DeploymentConfig {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressWhiteList) DeepCopyInto(out *EgressWhiteList) {
	*out = *in
	if in.IncludeIPRanges != nil {
		in, out := &in.IncludeIPRanges, &out.IncludeIPRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeIPRanges != nil {
		in, out := &in.ExcludeIPRanges, &out.ExcludeIPRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressWhiteList.
func (in *EgressWhiteList) DeepCopy() *EgressWhiteList {
	if in == nil {
		return nil
	}
	out := new(EgressWhiteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalleyConfig) DeepCopyInto(out *GalleyConfig) {
	*out = *in
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalleyConfig.
func (in *GalleyConfig) DeepCopy() *GalleyConfig {
	if in == nil {
		return nil
	}
	out := new(GalleyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaysConfig) DeepCopyInto(out *GatewaysConfig) {
	*out = *in
	if in.IngressGateway != nil {
		in, out := &in.IngressGateway, &out.IngressGateway
		if *in == nil {
			*out = nil
		} else {
			*out = new(CommonGatewayConfig)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.EgressGateway != nil {
		in, out := &in.EgressGateway, &out.EgressGateway
		if *in == nil {
			*out = nil
		} else {
			*out = new(CommonGatewayConfig)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaysConfig.
func (in *GatewaysConfig) DeepCopy() *GatewaysConfig {
	if in == nil {
		return nil
	}
	out := new(GatewaysConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralConfig) DeepCopyInto(out *GeneralConfig) {
	*out = *in
	in.DeploymentDefaults.DeepCopyInto(&out.DeploymentDefaults)
	in.PodSchedulingPrefs.DeepCopyInto(&out.PodSchedulingPrefs)
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		if *in == nil {
			*out = nil
		} else {
			*out = new(DebugConfig)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralConfig.
func (in *GeneralConfig) DeepCopy() *GeneralConfig {
	if in == nil {
		return nil
	}
	out := new(GeneralConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfig) DeepCopyInto(out *ImageConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfig.
func (in *ImageConfig) DeepCopy() *ImageConfig {
	if in == nil {
		return nil
	}
	out := new(ImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressWhiteList) DeepCopyInto(out *IngressWhiteList) {
	*out = *in
	if in.IncludePorts != nil {
		in, out := &in.IncludePorts, &out.IncludePorts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludePorts != nil {
		in, out := &in.ExcludePorts, &out.ExcludePorts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressWhiteList.
func (in *IngressWhiteList) DeepCopy() *IngressWhiteList {
	if in == nil {
		return nil
	}
	out := new(IngressWhiteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioControlPlane) DeepCopyInto(out *IstioControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioControlPlane.
func (in *IstioControlPlane) DeepCopy() *IstioControlPlane {
	if in == nil {
		return nil
	}
	out := new(IstioControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IstioControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioControlPlaneSpec) DeepCopyInto(out *IstioControlPlaneSpec) {
	*out = *in
	out.OperatorSpec = in.OperatorSpec
	in.General.DeepCopyInto(&out.General)
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	in.Security.DeepCopyInto(&out.Security)
	in.Galley.DeepCopyInto(&out.Galley)
	in.Pilot.DeepCopyInto(&out.Pilot)
	in.Proxy.DeepCopyInto(&out.Proxy)
	in.SidecarInjector.DeepCopyInto(&out.SidecarInjector)
	if in.Gateways != nil {
		in, out := &in.Gateways, &out.Gateways
		if *in == nil {
			*out = nil
		} else {
			*out = new(GatewaysConfig)
			(*in).DeepCopyInto(*out)
		}
	}
	in.Mixer.DeepCopyInto(&out.Mixer)
	if in.PrometheusConfig != nil {
		in, out := &in.PrometheusConfig, &out.PrometheusConfig
		if *in == nil {
			*out = nil
		} else {
			*out = new(PrometheusConfig)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioControlPlaneSpec.
func (in *IstioControlPlaneSpec) DeepCopy() *IstioControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(IstioControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioControlPlaneStatus) DeepCopyInto(out *IstioControlPlaneStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioControlPlaneStatus.
func (in *IstioControlPlaneStatus) DeepCopy() *IstioControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(IstioControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesEnvMixerAdapterConfig) DeepCopyInto(out *KubernetesEnvMixerAdapterConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesEnvMixerAdapterConfig.
func (in *KubernetesEnvMixerAdapterConfig) DeepCopy() *KubernetesEnvMixerAdapterConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesEnvMixerAdapterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LightStepConfig) DeepCopyInto(out *LightStepConfig) {
	*out = *in
	if in.Secure != nil {
		in, out := &in.Secure, &out.Secure
		if *in == nil {
			*out = nil
		} else {
			*out = new(bool)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LightStepConfig.
func (in *LightStepConfig) DeepCopy() *LightStepConfig {
	if in == nil {
		return nil
	}
	out := new(LightStepConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerAdapterConfig) DeepCopyInto(out *MixerAdapterConfig) {
	*out = *in
	if in.KubernetesEnv != nil {
		in, out := &in.KubernetesEnv, &out.KubernetesEnv
		if *in == nil {
			*out = nil
		} else {
			*out = new(KubernetesEnvMixerAdapterConfig)
			**out = **in
		}
	}
	if in.Stdio != nil {
		in, out := &in.Stdio, &out.Stdio
		if *in == nil {
			*out = nil
		} else {
			*out = new(StdioMixerAdapterConfig)
			**out = **in
		}
	}
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		if *in == nil {
			*out = nil
		} else {
			*out = new(PrometheusMixerAdapterConfig)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerAdapterConfig.
func (in *MixerAdapterConfig) DeepCopy() *MixerAdapterConfig {
	if in == nil {
		return nil
	}
	out := new(MixerAdapterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerConfig) DeepCopyInto(out *MixerConfig) {
	*out = *in
	in.Policy.DeepCopyInto(&out.Policy)
	in.Telemetry.DeepCopyInto(&out.Telemetry)
	if in.Adapters != nil {
		in, out := &in.Adapters, &out.Adapters
		*out = make([]MixerAdapterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerConfig.
func (in *MixerConfig) DeepCopy() *MixerConfig {
	if in == nil {
		return nil
	}
	out := new(MixerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfig) DeepCopyInto(out *MonitoringConfig) {
	*out = *in
	if in.EnableTracing != nil {
		in, out := &in.EnableTracing, &out.EnableTracing
		if *in == nil {
			*out = nil
		} else {
			*out = new(bool)
			**out = **in
		}
	}
	in.Tracer.DeepCopyInto(&out.Tracer)
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfig.
func (in *MonitoringConfig) DeepCopy() *MonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotConfig) DeepCopyInto(out *PilotConfig) {
	*out = *in
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
	if in.WatchedNamespaces != nil {
		in, out := &in.WatchedNamespaces, &out.WatchedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RandomTraceSampling != nil {
		in, out := &in.RandomTraceSampling, &out.RandomTraceSampling
		if *in == nil {
			*out = nil
		} else {
			*out = new(float64)
			**out = **in
		}
	}
	if in.Sidecar != nil {
		in, out := &in.Sidecar, &out.Sidecar
		if *in == nil {
			*out = nil
		} else {
			*out = new(bool)
			**out = **in
		}
	}
	if in.PushThrottleCount != nil {
		in, out := &in.PushThrottleCount, &out.PushThrottleCount
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotConfig.
func (in *PilotConfig) DeepCopy() *PilotConfig {
	if in == nil {
		return nil
	}
	out := new(PilotConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConfig) DeepCopyInto(out *PrometheusConfig) {
	*out = *in
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConfig.
func (in *PrometheusConfig) DeepCopy() *PrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusMixerAdapterConfig) DeepCopyInto(out *PrometheusMixerAdapterConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusMixerAdapterConfig.
func (in *PrometheusMixerAdapterConfig) DeepCopy() *PrometheusMixerAdapterConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusMixerAdapterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyConfig) DeepCopyInto(out *ProxyConfig) {
	*out = *in
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
	in.InitContainer.DeepCopyInto(&out.InitContainer)
	if in.EgressWhiteList != nil {
		in, out := &in.EgressWhiteList, &out.EgressWhiteList
		if *in == nil {
			*out = nil
		} else {
			*out = new(EgressWhiteList)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.IngressWhiteList != nil {
		in, out := &in.IngressWhiteList, &out.IngressWhiteList
		if *in == nil {
			*out = nil
		} else {
			*out = new(IngressWhiteList)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfig.
func (in *ProxyConfig) DeepCopy() *ProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfig) DeepCopyInto(out *SecurityConfig) {
	*out = *in
	in.Citadel.DeepCopyInto(&out.Citadel)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfig.
func (in *SecurityConfig) DeepCopy() *SecurityConfig {
	if in == nil {
		return nil
	}
	out := new(SecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarInjectorConfig) DeepCopyInto(out *SidecarInjectorConfig) {
	*out = *in
	in.DeploymentConfig.DeepCopyInto(&out.DeploymentConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarInjectorConfig.
func (in *SidecarInjectorConfig) DeepCopy() *SidecarInjectorConfig {
	if in == nil {
		return nil
	}
	out := new(SidecarInjectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusConfig) DeepCopyInto(out *StatusConfig) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	if in.InitialDelaySeconds != nil {
		in, out := &in.InitialDelaySeconds, &out.InitialDelaySeconds
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	if in.PeriodSeconds != nil {
		in, out := &in.PeriodSeconds, &out.PeriodSeconds
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	if in.SuccessThreshold != nil {
		in, out := &in.SuccessThreshold, &out.SuccessThreshold
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	if in.FailureThreshold != nil {
		in, out := &in.FailureThreshold, &out.FailureThreshold
		if *in == nil {
			*out = nil
		} else {
			*out = new(int32)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusConfig.
func (in *StatusConfig) DeepCopy() *StatusConfig {
	if in == nil {
		return nil
	}
	out := new(StatusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StdioMixerAdapterConfig) DeepCopyInto(out *StdioMixerAdapterConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StdioMixerAdapterConfig.
func (in *StdioMixerAdapterConfig) DeepCopy() *StdioMixerAdapterConfig {
	if in == nil {
		return nil
	}
	out := new(StdioMixerAdapterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracerConfig) DeepCopyInto(out *TracerConfig) {
	*out = *in
	if in.LightStep != nil {
		in, out := &in.LightStep, &out.LightStep
		if *in == nil {
			*out = nil
		} else {
			*out = new(LightStepConfig)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Zipkin != nil {
		in, out := &in.Zipkin, &out.Zipkin
		if *in == nil {
			*out = nil
		} else {
			*out = new(ZipkinConfig)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracerConfig.
func (in *TracerConfig) DeepCopy() *TracerConfig {
	if in == nil {
		return nil
	}
	out := new(TracerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZipkinConfig) DeepCopyInto(out *ZipkinConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZipkinConfig.
func (in *ZipkinConfig) DeepCopy() *ZipkinConfig {
	if in == nil {
		return nil
	}
	out := new(ZipkinConfig)
	in.DeepCopyInto(out)
	return out
}
