{{ $gateway := index .Values "gateways" "istio-egressgateway" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $gateway.name | default "istio-egressgateway" }}

{{- if or (not $gateway.namespace) (eq $gateway.name "istio-egressgateway") }}
  namespace: {{ .Release.Namespace }}
{{- else }}
  namespace: {{ $gateway.namespace }}
{{- end }}
  annotations:
    {{- range $key, $val := $gateway.serviceAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    maistra-version: 2.0.0
{{ $gateway.labels | toYaml | indent 4 }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
{{ $gateway.labels | toYaml | indent 4 }}
  ports:
    {{- range $key, $val := $gateway.ports }}
    -
      {{- range $pkey, $pval := $val }}
      {{ $pkey }}: {{ $pval }}
      {{- end }}
    {{- end }}
---
