package v1alpha3

import (
	"encoding/json"

	"github.com/gogo/protobuf/jsonpb"
	meshv1alpha1 "istio.io/api/mesh/v1alpha1"
)

// DeepCopyInto is a custom deepcopy function for MeshNetworksType, copying the receiver, writing into out. in must be non-nil.
func (in MeshNetworksType) DeepCopyInto(out *MeshNetworksType) {
	{
		in := &in
		*out = make(MeshNetworksType, len(*in))
		for key, val := range *in {
			(*out)[key] = deepCopyMeshNetwork(val)
		}
		return
	}
}

func deepCopyMeshNetwork(in meshv1alpha1.Network) meshv1alpha1.Network {
	data, err := in.Marshal()
	if err != nil {
		// panic???
		return meshv1alpha1.Network{}
	}
	out := meshv1alpha1.Network{}
	err = out.Unmarshal(data)
	if err != nil {
		// panic???
		return out
	}
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ReleaseInfoType) DeepCopyInto(out *ReleaseInfoType) {
    *out = ReleaseInfoType{}
    data, err := json.Marshal(in)
    if err != nil {
        // panic ???
        return
    }
    err = json.Unmarshal(data, out)
    if err != nil {
        // panic ???
        return
    }
    return
}

var (
	jsonpbMarshaler   = jsonpb.Marshaler{}
	jsonpbUnmarshaler = jsonpb.Unmarshaler{}
)
