// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha3

import (
	v1 "k8s.io/api/core/v1"
	v1beta1 "k8s.io/api/extensions/v1beta1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AnnotationsType) DeepCopyInto(out *AnnotationsType) {
	{
		in := &in
		*out = make(AnnotationsType, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnotationsType.
func (in AnnotationsType) DeepCopy() AnnotationsType {
	if in == nil {
		return nil
	}
	out := new(AnnotationsType)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonComponentConfig) DeepCopyInto(out *CommonComponentConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	out.NameOverrides = in.NameOverrides
	in.Global.DeepCopyInto(&out.Global)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonComponentConfig.
func (in *CommonComponentConfig) DeepCopy() *CommonComponentConfig {
	if in == nil {
		return nil
	}
	out := new(CommonComponentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapVolume) DeepCopyInto(out *ConfigMapVolume) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapVolume.
func (in *ConfigMapVolume) DeepCopy() *ConfigMapVolume {
	if in == nil {
		return nil
	}
	out := new(ConfigMapVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentFields) DeepCopyInto(out *DeploymentFields) {
	*out = *in
	in.HorizontalPodAutoscalerFields.DeepCopyInto(&out.HorizontalPodAutoscalerFields)
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(AnnotationsType, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentFields.
func (in *DeploymentFields) DeepCopy() *DeploymentFields {
	if in == nil {
		return nil
	}
	out := new(DeploymentFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnabledField) DeepCopyInto(out *EnabledField) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnabledField.
func (in *EnabledField) DeepCopy() *EnabledField {
	if in == nil {
		return nil
	}
	out := new(EnabledField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyStatsDConfig) DeepCopyInto(out *EnvoyStatsDConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyStatsDConfig.
func (in *EnvoyStatsDConfig) DeepCopy() *EnvoyStatsDConfig {
	if in == nil {
		return nil
	}
	out := new(EnvoyStatsDConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalleyConfig) DeepCopyInto(out *GalleyConfig) {
	*out = *in
	in.CommonComponentConfig.DeepCopyInto(&out.CommonComponentConfig)
	in.DeploymentFields.DeepCopyInto(&out.DeploymentFields)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalleyConfig.
func (in *GalleyConfig) DeepCopy() *GalleyConfig {
	if in == nil {
		return nil
	}
	out := new(GalleyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfig) DeepCopyInto(out *GatewayConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	in.DeploymentFields.DeepCopyInto(&out.DeploymentFields)
	if in.AdditionalContainers != nil {
		in, out := &in.AdditionalContainers, &out.AdditionalContainers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfigVolumes != nil {
		in, out := &in.ConfigVolumes, &out.ConfigVolumes
		*out = make([]ConfigMapVolume, len(*in))
		copy(*out, *in)
	}
	in.SDS.DeepCopyInto(&out.SDS)
	if in.SecretVolumes != nil {
		in, out := &in.SecretVolumes, &out.SecretVolumes
		*out = make([]SecretVolume, len(*in))
		copy(*out, *in)
	}
	if in.ExternalIPs != nil {
		in, out := &in.ExternalIPs, &out.ExternalIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LoadBalancerSourceRanges != nil {
		in, out := &in.LoadBalancerSourceRanges, &out.LoadBalancerSourceRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MeshExpansionPorts != nil {
		in, out := &in.MeshExpansionPorts, &out.MeshExpansionPorts
		*out = make([]v1.ServicePort, len(*in))
		copy(*out, *in)
	}
	if in.ServiceAnnotations != nil {
		in, out := &in.ServiceAnnotations, &out.ServiceAnnotations
		*out = make(AnnotationsType, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]v1.ServicePort, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfig.
func (in *GatewayConfig) DeepCopy() *GatewayConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaysConfig) DeepCopyInto(out *GatewaysConfig) {
	*out = *in
	in.CommonComponentConfig.DeepCopyInto(&out.CommonComponentConfig)
	if in.Gateways != nil {
		in, out := &in.Gateways, &out.Gateways
		*out = make(map[string]GatewayConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaysConfig.
func (in *GatewaysConfig) DeepCopy() *GatewaysConfig {
	if in == nil {
		return nil
	}
	out := new(GatewaysConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalConfig) DeepCopyInto(out *GlobalConfig) {
	*out = *in
	if in.Arch != nil {
		in, out := &in.Arch, &out.Arch
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigValidation != nil {
		in, out := &in.ConfigValidation, &out.ConfigValidation
		*out = new(bool)
		**out = **in
	}
	if in.ControlPlaneSecurityEnabled != nil {
		in, out := &in.ControlPlaneSecurityEnabled, &out.ControlPlaneSecurityEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CreateRemoteSvcEndpoints != nil {
		in, out := &in.CreateRemoteSvcEndpoints, &out.CreateRemoteSvcEndpoints
		*out = new(bool)
		**out = **in
	}
	if in.RemotePilotCreateSvcEndpoint != nil {
		in, out := &in.RemotePilotCreateSvcEndpoint, &out.RemotePilotCreateSvcEndpoint
		*out = new(bool)
		**out = **in
	}
	if in.IstioRemote != nil {
		in, out := &in.IstioRemote, &out.IstioRemote
		*out = new(bool)
		**out = **in
	}
	if in.DefaultConfigVisibilitySettings != nil {
		in, out := &in.DefaultConfigVisibilitySettings, &out.DefaultConfigVisibilitySettings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultNodeSelector != nil {
		in, out := &in.DefaultNodeSelector, &out.DefaultNodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.DefaultPodDisruptionBudget.DeepCopyInto(&out.DefaultPodDisruptionBudget)
	in.DefaultResources.DeepCopyInto(&out.DefaultResources)
	if in.DisablePolicyChecks != nil {
		in, out := &in.DisablePolicyChecks, &out.DisablePolicyChecks
		*out = new(bool)
		**out = **in
	}
	if in.EnableTracing != nil {
		in, out := &in.EnableTracing, &out.EnableTracing
		*out = new(bool)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	in.KubernetesIngress.DeepCopyInto(&out.KubernetesIngress)
	in.MeshExpansion.DeepCopyInto(&out.MeshExpansion)
	out.MeshNetworks = in.MeshNetworks.DeepCopy()
	if in.MonitoringPort != nil {
		in, out := &in.MonitoringPort, &out.MonitoringPort
		*out = new(int32)
		**out = **in
	}
	in.MTLS.DeepCopyInto(&out.MTLS)
	in.MultiCluster.DeepCopyInto(&out.MultiCluster)
	if in.OmitSidecarInjectorConfigMap != nil {
		in, out := &in.OmitSidecarInjectorConfigMap, &out.OmitSidecarInjectorConfigMap
		*out = new(bool)
		**out = **in
	}
	if in.OneNamespace != nil {
		in, out := &in.OneNamespace, &out.OneNamespace
		*out = new(bool)
		**out = **in
	}
	out.OutboundTrafficPolicy = in.OutboundTrafficPolicy
	if in.PodDNSSearchNamespaces != nil {
		in, out := &in.PodDNSSearchNamespaces, &out.PodDNSSearchNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicyCheckFailOpen != nil {
		in, out := &in.PolicyCheckFailOpen, &out.PolicyCheckFailOpen
		*out = new(bool)
		**out = **in
	}
	if in.UseMCP != nil {
		in, out := &in.UseMCP, &out.UseMCP
		*out = new(bool)
		**out = **in
	}
	in.Proxy.DeepCopyInto(&out.Proxy)
	in.ProxyInit.DeepCopyInto(&out.ProxyInit)
	in.SDS.DeepCopyInto(&out.SDS)
	in.Tracer.DeepCopyInto(&out.Tracer)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalConfig.
func (in *GlobalConfig) DeepCopy() *GlobalConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalPodAutoscalerFields) DeepCopyInto(out *HorizontalPodAutoscalerFields) {
	*out = *in
	if in.AutoscaleEnabled != nil {
		in, out := &in.AutoscaleEnabled, &out.AutoscaleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AutoscaleMax != nil {
		in, out := &in.AutoscaleMax, &out.AutoscaleMax
		*out = new(int32)
		**out = **in
	}
	if in.AutoscaleMin != nil {
		in, out := &in.AutoscaleMin, &out.AutoscaleMin
		*out = new(int32)
		**out = **in
	}
	in.CPU.DeepCopyInto(&out.CPU)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalPodAutoscalerFields.
func (in *HorizontalPodAutoscalerFields) DeepCopy() *HorizontalPodAutoscalerFields {
	if in == nil {
		return nil
	}
	out := new(HorizontalPodAutoscalerFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioControlPlane) DeepCopyInto(out *IstioControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioControlPlane.
func (in *IstioControlPlane) DeepCopy() *IstioControlPlane {
	if in == nil {
		return nil
	}
	out := new(IstioControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IstioControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioControlPlaneList) DeepCopyInto(out *IstioControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IstioControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioControlPlaneList.
func (in *IstioControlPlaneList) DeepCopy() *IstioControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(IstioControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IstioControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioControlPlaneSpec) DeepCopyInto(out *IstioControlPlaneSpec) {
	*out = *in
	in.Global.DeepCopyInto(&out.Global)
	in.Galley.DeepCopyInto(&out.Galley)
	in.Gateways.DeepCopyInto(&out.Gateways)
	in.Mixer.DeepCopyInto(&out.Mixer)
	in.Pilot.DeepCopyInto(&out.Pilot)
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	in.Security.DeepCopyInto(&out.Security)
	in.SidecarInjector.DeepCopyInto(&out.SidecarInjector)
	in.Tracing.DeepCopyInto(&out.Tracing)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioControlPlaneSpec.
func (in *IstioControlPlaneSpec) DeepCopy() *IstioControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(IstioControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioControlPlaneStatus) DeepCopyInto(out *IstioControlPlaneStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioControlPlaneStatus.
func (in *IstioControlPlaneStatus) DeepCopy() *IstioControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(IstioControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesEnvMixerAdapterConfig) DeepCopyInto(out *KubernetesEnvMixerAdapterConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesEnvMixerAdapterConfig.
func (in *KubernetesEnvMixerAdapterConfig) DeepCopy() *KubernetesEnvMixerAdapterConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesEnvMixerAdapterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesIngressConfig) DeepCopyInto(out *KubernetesIngressConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	if in.EnableHTTPS != nil {
		in, out := &in.EnableHTTPS, &out.EnableHTTPS
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesIngressConfig.
func (in *KubernetesIngressConfig) DeepCopy() *KubernetesIngressConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesIngressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MTLSConfig) DeepCopyInto(out *MTLSConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MTLSConfig.
func (in *MTLSConfig) DeepCopy() *MTLSConfig {
	if in == nil {
		return nil
	}
	out := new(MTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshExpansionConfig) DeepCopyInto(out *MeshExpansionConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	if in.UseILB != nil {
		in, out := &in.UseILB, &out.UseILB
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshExpansionConfig.
func (in *MeshExpansionConfig) DeepCopy() *MeshExpansionConfig {
	if in == nil {
		return nil
	}
	out := new(MeshExpansionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshNetworksType.
func (in MeshNetworksType) DeepCopy() MeshNetworksType {
	if in == nil {
		return nil
	}
	out := new(MeshNetworksType)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerAdaptersConfig) DeepCopyInto(out *MixerAdaptersConfig) {
	*out = *in
	in.KubernetesEnv.DeepCopyInto(&out.KubernetesEnv)
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	in.Stdio.DeepCopyInto(&out.Stdio)
	if in.UseAdapterCRDs != nil {
		in, out := &in.UseAdapterCRDs, &out.UseAdapterCRDs
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerAdaptersConfig.
func (in *MixerAdaptersConfig) DeepCopy() *MixerAdaptersConfig {
	if in == nil {
		return nil
	}
	out := new(MixerAdaptersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerConfig) DeepCopyInto(out *MixerConfig) {
	*out = *in
	in.CommonComponentConfig.DeepCopyInto(&out.CommonComponentConfig)
	in.DeploymentFields.DeepCopyInto(&out.DeploymentFields)
	in.Policy.DeepCopyInto(&out.Policy)
	in.Telemetry.DeepCopyInto(&out.Telemetry)
	in.Adapters.DeepCopyInto(&out.Adapters)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerConfig.
func (in *MixerConfig) DeepCopy() *MixerConfig {
	if in == nil {
		return nil
	}
	out := new(MixerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerTelemetryConfig) DeepCopyInto(out *MixerTelemetryConfig) {
	*out = *in
	in.DeploymentFields.DeepCopyInto(&out.DeploymentFields)
	if in.SessionAffinityEnabled != nil {
		in, out := &in.SessionAffinityEnabled, &out.SessionAffinityEnabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerTelemetryConfig.
func (in *MixerTelemetryConfig) DeepCopy() *MixerTelemetryConfig {
	if in == nil {
		return nil
	}
	out := new(MixerTelemetryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterConfig) DeepCopyInto(out *MultiClusterConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterConfig.
func (in *MultiClusterConfig) DeepCopy() *MultiClusterConfig {
	if in == nil {
		return nil
	}
	out := new(MultiClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameOverrides) DeepCopyInto(out *NameOverrides) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameOverrides.
func (in *NameOverrides) DeepCopy() *NameOverrides {
	if in == nil {
		return nil
	}
	out := new(NameOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundTrafficPolicyConfig) DeepCopyInto(out *OutboundTrafficPolicyConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundTrafficPolicyConfig.
func (in *OutboundTrafficPolicyConfig) DeepCopy() *OutboundTrafficPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(OutboundTrafficPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotConfig) DeepCopyInto(out *PilotConfig) {
	*out = *in
	in.CommonComponentConfig.DeepCopyInto(&out.CommonComponentConfig)
	in.DeploymentFields.DeepCopyInto(&out.DeploymentFields)
	if in.Sidecar != nil {
		in, out := &in.Sidecar, &out.Sidecar
		*out = new(bool)
		**out = **in
	}
	if in.TraceSampling != nil {
		in, out := &in.TraceSampling, &out.TraceSampling
		*out = new(float64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotConfig.
func (in *PilotConfig) DeepCopy() *PilotConfig {
	if in == nil {
		return nil
	}
	out := new(PilotConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDisruptionBudget) DeepCopyInto(out *PodDisruptionBudget) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	in.PodDisruptionBudget.DeepCopyInto(&out.PodDisruptionBudget)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDisruptionBudget.
func (in *PodDisruptionBudget) DeepCopy() *PodDisruptionBudget {
	if in == nil {
		return nil
	}
	out := new(PodDisruptionBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConfig) DeepCopyInto(out *PrometheusConfig) {
	*out = *in
	in.CommonComponentConfig.DeepCopyInto(&out.CommonComponentConfig)
	in.DeploymentFields.DeepCopyInto(&out.DeploymentFields)
	in.Gateway.DeepCopyInto(&out.Gateway)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Security.DeepCopyInto(&out.Security)
	in.Service.DeepCopyInto(&out.Service)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConfig.
func (in *PrometheusConfig) DeepCopy() *PrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusGatewayConfig) DeepCopyInto(out *PrometheusGatewayConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusGatewayConfig.
func (in *PrometheusGatewayConfig) DeepCopy() *PrometheusGatewayConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusIngressConfig) DeepCopyInto(out *PrometheusIngressConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(AnnotationsType, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make([]v1beta1.IngressTLS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusIngressConfig.
func (in *PrometheusIngressConfig) DeepCopy() *PrometheusIngressConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusIngressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusMixerAdapterConfig) DeepCopyInto(out *PrometheusMixerAdapterConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusMixerAdapterConfig.
func (in *PrometheusMixerAdapterConfig) DeepCopy() *PrometheusMixerAdapterConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusMixerAdapterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusSecurityConfig) DeepCopyInto(out *PrometheusSecurityConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusSecurityConfig.
func (in *PrometheusSecurityConfig) DeepCopy() *PrometheusSecurityConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusSecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusServiceConfig) DeepCopyInto(out *PrometheusServiceConfig) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(AnnotationsType, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.NodePort.DeepCopyInto(&out.NodePort)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusServiceConfig.
func (in *PrometheusServiceConfig) DeepCopy() *PrometheusServiceConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusServiceNodePortConfig) DeepCopyInto(out *PrometheusServiceNodePortConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusServiceNodePortConfig.
func (in *PrometheusServiceNodePortConfig) DeepCopy() *PrometheusServiceNodePortConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusServiceNodePortConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyConfig) DeepCopyInto(out *ProxyConfig) {
	*out = *in
	if in.AutoInject != nil {
		in, out := &in.AutoInject, &out.AutoInject
		*out = new(bool)
		**out = **in
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(int32)
		**out = **in
	}
	if in.EnableCoreDump != nil {
		in, out := &in.EnableCoreDump, &out.EnableCoreDump
		*out = new(bool)
		**out = **in
	}
	if in.Privileged != nil {
		in, out := &in.Privileged, &out.Privileged
		*out = new(bool)
		**out = **in
	}
	if in.ReadinessFailureThreshold != nil {
		in, out := &in.ReadinessFailureThreshold, &out.ReadinessFailureThreshold
		*out = new(int32)
		**out = **in
	}
	if in.ReadinessInitialDelaySeconds != nil {
		in, out := &in.ReadinessInitialDelaySeconds, &out.ReadinessInitialDelaySeconds
		*out = new(int32)
		**out = **in
	}
	if in.ReadinessPeriodSeconds != nil {
		in, out := &in.ReadinessPeriodSeconds, &out.ReadinessPeriodSeconds
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.StatusPort != nil {
		in, out := &in.StatusPort, &out.StatusPort
		*out = new(int32)
		**out = **in
	}
	in.EnvoyStatsD.DeepCopyInto(&out.EnvoyStatsD)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfig.
func (in *ProxyConfig) DeepCopy() *ProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyInitConfig) DeepCopyInto(out *ProxyInitConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyInitConfig.
func (in *ProxyInitConfig) DeepCopy() *ProxyInitConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyInitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTracerConfig) DeepCopyInto(out *ProxyTracerConfig) {
	*out = *in
	if in.LightStep != nil {
		in, out := &in.LightStep, &out.LightStep
		*out = new(ProxyTracerLightStepConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Zipkin != nil {
		in, out := &in.Zipkin, &out.Zipkin
		*out = new(ProxyTracerZipkinConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTracerConfig.
func (in *ProxyTracerConfig) DeepCopy() *ProxyTracerConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyTracerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTracerLightStepConfig) DeepCopyInto(out *ProxyTracerLightStepConfig) {
	*out = *in
	if in.Secure != nil {
		in, out := &in.Secure, &out.Secure
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTracerLightStepConfig.
func (in *ProxyTracerLightStepConfig) DeepCopy() *ProxyTracerLightStepConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyTracerLightStepConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTracerZipkinConfig) DeepCopyInto(out *ProxyTracerZipkinConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTracerZipkinConfig.
func (in *ProxyTracerZipkinConfig) DeepCopy() *ProxyTracerZipkinConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyTracerZipkinConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceMetricCPU) DeepCopyInto(out *ResourceMetricCPU) {
	*out = *in
	if in.TargetAverageUtilization != nil {
		in, out := &in.TargetAverageUtilization, &out.TargetAverageUtilization
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceMetricCPU.
func (in *ResourceMetricCPU) DeepCopy() *ResourceMetricCPU {
	if in == nil {
		return nil
	}
	out := new(ResourceMetricCPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDSConfig) DeepCopyInto(out *SDSConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	if in.UseNormalJWT != nil {
		in, out := &in.UseNormalJWT, &out.UseNormalJWT
		*out = new(bool)
		**out = **in
	}
	if in.UseTrustworthyJWT != nil {
		in, out := &in.UseTrustworthyJWT, &out.UseTrustworthyJWT
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDSConfig.
func (in *SDSConfig) DeepCopy() *SDSConfig {
	if in == nil {
		return nil
	}
	out := new(SDSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDSContainerConfig) DeepCopyInto(out *SDSContainerConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDSContainerConfig.
func (in *SDSContainerConfig) DeepCopy() *SDSContainerConfig {
	if in == nil {
		return nil
	}
	out := new(SDSContainerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretVolume) DeepCopyInto(out *SecretVolume) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretVolume.
func (in *SecretVolume) DeepCopy() *SecretVolume {
	if in == nil {
		return nil
	}
	out := new(SecretVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfig) DeepCopyInto(out *SecurityConfig) {
	*out = *in
	in.CommonComponentConfig.DeepCopyInto(&out.CommonComponentConfig)
	in.DeploymentFields.DeepCopyInto(&out.DeploymentFields)
	if in.SelfSigned != nil {
		in, out := &in.SelfSigned, &out.SelfSigned
		*out = new(bool)
		**out = **in
	}
	if in.CreateMeshPolicy != nil {
		in, out := &in.CreateMeshPolicy, &out.CreateMeshPolicy
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfig.
func (in *SecurityConfig) DeepCopy() *SecurityConfig {
	if in == nil {
		return nil
	}
	out := new(SecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarInjectorConfig) DeepCopyInto(out *SidecarInjectorConfig) {
	*out = *in
	in.CommonComponentConfig.DeepCopyInto(&out.CommonComponentConfig)
	in.DeploymentFields.DeepCopyInto(&out.DeploymentFields)
	if in.EnableNamespacesByDefault != nil {
		in, out := &in.EnableNamespacesByDefault, &out.EnableNamespacesByDefault
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarInjectorConfig.
func (in *SidecarInjectorConfig) DeepCopy() *SidecarInjectorConfig {
	if in == nil {
		return nil
	}
	out := new(SidecarInjectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StdioMixerAdapterConfig) DeepCopyInto(out *StdioMixerAdapterConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	if in.OutputAsJSON != nil {
		in, out := &in.OutputAsJSON, &out.OutputAsJSON
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StdioMixerAdapterConfig.
func (in *StdioMixerAdapterConfig) DeepCopy() *StdioMixerAdapterConfig {
	if in == nil {
		return nil
	}
	out := new(StdioMixerAdapterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingConfig) DeepCopyInto(out *TracingConfig) {
	*out = *in
	in.CommonComponentConfig.DeepCopyInto(&out.CommonComponentConfig)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Gateway.DeepCopyInto(&out.Gateway)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Jaeger.DeepCopyInto(&out.Jaeger)
	in.Service.DeepCopyInto(&out.Service)
	in.Zipkin.DeepCopyInto(&out.Zipkin)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingConfig.
func (in *TracingConfig) DeepCopy() *TracingConfig {
	if in == nil {
		return nil
	}
	out := new(TracingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingGatewayConfig) DeepCopyInto(out *TracingGatewayConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingGatewayConfig.
func (in *TracingGatewayConfig) DeepCopy() *TracingGatewayConfig {
	if in == nil {
		return nil
	}
	out := new(TracingGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingIngressConfig) DeepCopyInto(out *TracingIngressConfig) {
	*out = *in
	in.EnabledField.DeepCopyInto(&out.EnabledField)
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(AnnotationsType, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make([]v1beta1.IngressTLS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingIngressConfig.
func (in *TracingIngressConfig) DeepCopy() *TracingIngressConfig {
	if in == nil {
		return nil
	}
	out := new(TracingIngressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingJaegerConfig) DeepCopyInto(out *TracingJaegerConfig) {
	*out = *in
	out.Memory = in.Memory
	in.Resources.DeepCopyInto(&out.Resources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingJaegerConfig.
func (in *TracingJaegerConfig) DeepCopy() *TracingJaegerConfig {
	if in == nil {
		return nil
	}
	out := new(TracingJaegerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingJaegerMemoryConfig) DeepCopyInto(out *TracingJaegerMemoryConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingJaegerMemoryConfig.
func (in *TracingJaegerMemoryConfig) DeepCopy() *TracingJaegerMemoryConfig {
	if in == nil {
		return nil
	}
	out := new(TracingJaegerMemoryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingServiceConfig) DeepCopyInto(out *TracingServiceConfig) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(AnnotationsType, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingServiceConfig.
func (in *TracingServiceConfig) DeepCopy() *TracingServiceConfig {
	if in == nil {
		return nil
	}
	out := new(TracingServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingZipkinConfig) DeepCopyInto(out *TracingZipkinConfig) {
	*out = *in
	out.Node = in.Node
	in.Resources.DeepCopyInto(&out.Resources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingZipkinConfig.
func (in *TracingZipkinConfig) DeepCopy() *TracingZipkinConfig {
	if in == nil {
		return nil
	}
	out := new(TracingZipkinConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingZipkinNodeConfig) DeepCopyInto(out *TracingZipkinNodeConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingZipkinNodeConfig.
func (in *TracingZipkinNodeConfig) DeepCopy() *TracingZipkinNodeConfig {
	if in == nil {
		return nil
	}
	out := new(TracingZipkinNodeConfig)
	in.DeepCopyInto(out)
	return out
}
